services:
  whatsapp-bot:
    image: python:3.12-slim
    container_name: whatsapp-bot
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python main.py"
